"""refactored orders

Revision ID: 0929690f159f
Revises: d52e3d897e71
Create Date: 2026-04-03 15:19:10.733758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = "0929690f159f"
down_revision: Union[str, Sequence[str], None] = "d52e3d897e71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order",
        "qty",
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=False,
        postgresql_using="qty::double precision",
    )
    op.add_column("refreshtoken", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.alter_column("refreshtoken", "user_id", nullable=False)

    op.create_index(
        op.f("ix_refreshtoken_user_id"), "refreshtoken", ["user_id"], unique=False
    )
    op.create_foreign_key(None, "refreshtoken", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "refreshtoken", type_="foreignkey")
    op.drop_index(op.f("ix_refreshtoken_user_id"), table_name="refreshtoken")
    op.drop_column("refreshtoken", "user_id")
    op.alter_column(
        "order",
        "qty",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
