"""removed hashed secret key

Revision ID: 1b8b5d50a35f
Revises: 4bd7da205ad3
Create Date: 2026-03-12 17:38:07.471238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '1b8b5d50a35f'
down_revision: Union[str, Sequence[str], None] = '4bd7da205ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hashed_secret_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_secret_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
