"""initial migration

Revision ID: 4c4e4f18a6c8
Revises:
Create Date: 2026-01-23 00:19:56.096599

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4c4e4f18a6c8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_data",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("Open", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("High", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("Low", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("Close", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("Volume", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Dividends", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("Stock Splits", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("stock_data_pkey")),
        sa.UniqueConstraint(
            "symbol",
            "date",
            name=op.f("_symbol_date_uc"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("idx_symbol"), "stock_data", ["symbol"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "encrypted_api_key", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "encrypted_secret_key", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("idx_symbol"), table_name="stock_data")
    op.drop_table("stock_data")
    # ### end Alembic commands ###
