"""added timezone to refresh token expires at

Revision ID: 4e4725b79354
Revises: 5b94c02da7c6
Create Date: 2026-04-11 16:36:20.950676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4e4725b79354"
down_revision: Union[str, Sequence[str], None] = "5b94c02da7c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # add new columns first
    op.add_column(
        "order",
        sa.Column(
            "order_type",
            sa.Enum("MARKET", "LIMIT", "STOP", "STOP_LIMIT", name="ordertype"),
            nullable=False,
        ),
    )

    op.add_column(
        "order",
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )

    op.add_column(
        "order",
        sa.Column("alpaca_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )

    op.add_column(
        "order",
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    )

    # IMPORTANT: drop old column completely (no cast issues)
    op.drop_column("order", "side")

    # recreate clean enum column
    op.add_column(
        "order",
        sa.Column(
            "side",
            sa.Enum("BUY", "SELL", name="orderside"),
            nullable=False,
        ),
    )

    # refresh token fix
    op.alter_column(
        "refreshtoken",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
    )


# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refreshtoken",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
    )

    op.drop_column("order", "order_type")
    op.drop_column("order", "details")
    op.drop_column("order", "alpaca_status")
    op.drop_column("order", "updated_at")

    op.drop_column("order", "side")

    op.add_column(
        "order",
        sa.Column("side", sa.VARCHAR(), nullable=False),
    )
    # ### end Alembic commands ###
