"""created positions table
2


Revision ID: 5b94c02da7c6
Revises: acd2be86979b
Create Date: 2026-03-28 22:43:26.743784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '5b94c02da7c6'
down_revision: Union[str, Sequence[str], None] = 'acd2be86979b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('unrealised_pl', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_symbol'), 'position', ['symbol'], unique=False)
    op.create_index(op.f('ix_position_user_id'), 'position', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_user_id'), table_name='position')
    op.drop_index(op.f('ix_position_symbol'), table_name='position')
    op.drop_table('position')
    # ### end Alembic commands ###
