"""removed jti, created at, last used, columns from refresh token

Revision ID: 90769b5cbdf6
Revises: 2f92645f5311
Create Date: 2026-03-24 17:03:42.026819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90769b5cbdf6'
down_revision: Union[str, Sequence[str], None] = '2f92645f5311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refreshtoken_jti'), table_name='refreshtoken')
    op.drop_column('refreshtoken', 'created_at')
    op.drop_column('refreshtoken', 'jti')
    op.drop_column('refreshtoken', 'last_used_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtoken', sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('refreshtoken', sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('refreshtoken', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_refreshtoken_jti'), 'refreshtoken', ['jti'], unique=True)
    # ### end Alembic commands ###
