"""added order table

Revision ID: acd2be86979b
Revises: 90769b5cbdf6
Create Date: 2026-03-28 21:23:29.006570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = 'acd2be86979b'
down_revision: Union[str, Sequence[str], None] = '90769b5cbdf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('alpaca_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', 'TRAILING_STOP', name='ordertype'), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PARTIALLY_FILLED', 'FILLED', 'DONE_FOR_DAY', 'CANCELED', 'EXPIRED', 'REPLACED', 'PENDING_CANCEL', 'PENDING_REPLACE', 'PENDING_REVIEW', 'ACCEPTED', 'PENDING_NEW', 'ACCEPTED_FOR_BIDDING', 'STOPPED', 'REJECTED', 'SUSPENDED', 'CALCULATED', 'HELD', name='orderstatus'), nullable=False),
    sa.Column('alpaca_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_alpaca_order_id'), 'order', ['alpaca_order_id'], unique=False)
    op.create_index(op.f('ix_order_client_order_id'), 'order', ['client_order_id'], unique=False)
    op.create_index(op.f('ix_order_symbol'), 'order', ['symbol'], unique=False)
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_index(op.f('ix_order_symbol'), table_name='order')
    op.drop_index(op.f('ix_order_client_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_alpaca_order_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
