"""created orders and positions table

Revision ID: b26e97d0dee3
Revises: 0929690f159f
Create Date: 2026-04-03 15:33:16.891081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b26e97d0dee3'
down_revision: Union[str, Sequence[str], None] = '0929690f159f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('unrealised_pl', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_symbol'), 'position', ['symbol'], unique=False)
    op.create_index(op.f('ix_position_user_id'), 'position', ['user_id'], unique=False)
    op.add_column('order', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('order', sa.Column('time_in_force', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('order', sa.Column('filled_qty', sa.Float(), nullable=False))
    op.add_column('order', sa.Column('filled_avg_price', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('filled_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('canceled_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('extended_hours', sa.Boolean(), nullable=False))
    op.alter_column('order', 'side',
               existing_type=postgresql.ENUM('BUY', 'SELL', name='orderside'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('order', 'alpaca_order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_order_client_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_symbol'), table_name='order')
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_index(op.f('ix_order_alpaca_order_id'), table_name='order')
    op.create_index(op.f('ix_order_alpaca_order_id'), 'order', ['alpaca_order_id'], unique=True)
    op.drop_column('order', 'updated_at')
    op.drop_column('order', 'alpaca_status')
    op.drop_column('order', 'order_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_type', postgresql.ENUM('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', 'TRAILING_STOP', name='ordertype'), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('alpaca_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_order_alpaca_order_id'), table_name='order')
    op.create_index(op.f('ix_order_alpaca_order_id'), 'order', ['alpaca_order_id'], unique=False)
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    op.create_index(op.f('ix_order_symbol'), 'order', ['symbol'], unique=False)
    op.create_index(op.f('ix_order_client_order_id'), 'order', ['client_order_id'], unique=False)
    op.alter_column('order', 'alpaca_order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'side',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('BUY', 'SELL', name='orderside'),
               existing_nullable=False)
    op.drop_column('order', 'extended_hours')
    op.drop_column('order', 'canceled_at')
    op.drop_column('order', 'filled_at')
    op.drop_column('order', 'submitted_at')
    op.drop_column('order', 'filled_avg_price')
    op.drop_column('order', 'filled_qty')
    op.drop_column('order', 'time_in_force')
    op.drop_column('order', 'type')
    op.drop_index(op.f('ix_position_user_id'), table_name='position')
    op.drop_index(op.f('ix_position_symbol'), table_name='position')
    op.drop_table('position')
    # ### end Alembic commands ###
