"""created now order base and order table

Revision ID: d52e3d897e71
Revises: 5b94c02da7c6
Create Date: 2026-04-03 14:48:43.268243

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d52e3d897e71"
down_revision: Union[str, Sequence[str], None] = "5b94c02da7c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order", sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column(
        "order",
        sa.Column("time_in_force", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("order", sa.Column("filled_qty", sa.Float(), nullable=False))
    op.add_column("order", sa.Column("filled_avg_price", sa.Float(), nullable=True))
    op.add_column("order", sa.Column("submitted_at", sa.DateTime(), nullable=True))
    op.add_column("order", sa.Column("filled_at", sa.DateTime(), nullable=True))
    op.add_column("order", sa.Column("canceled_at", sa.DateTime(), nullable=True))
    op.add_column("order", sa.Column("extended_hours", sa.Boolean(), nullable=False))
    op.alter_column(
        "order",
        "qty",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
        postgresql_using="qty::double precision",
    )
    op.alter_column(
        "order",
        "side",
        existing_type=postgresql.ENUM("BUY", "SELL", name="orderside"),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "order", "alpaca_order_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_index(op.f("ix_order_client_order_id"), table_name="order")
    op.drop_index(op.f("ix_order_symbol"), table_name="order")
    op.drop_index(op.f("ix_order_user_id"), table_name="order")
    op.drop_index(op.f("ix_order_alpaca_order_id"), table_name="order")
    op.create_index(
        op.f("ix_order_alpaca_order_id"), "order", ["alpaca_order_id"], unique=True
    )
    op.drop_column("order", "updated_at")
    op.drop_column("order", "alpaca_status")
    op.drop_column("order", "order_type")
    op.drop_index(op.f("ix_refreshtoken_user_id"), table_name="refreshtoken")
    op.drop_constraint(
        op.f("refreshtoken_user_id_fkey"), "refreshtoken", type_="foreignkey"
    )
    op.drop_column("refreshtoken", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refreshtoken",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("refreshtoken_user_id_fkey"), "refreshtoken", "user", ["user_id"], ["id"]
    )
    op.create_index(
        op.f("ix_refreshtoken_user_id"), "refreshtoken", ["user_id"], unique=False
    )
    op.add_column(
        "order",
        sa.Column(
            "order_type",
            postgresql.ENUM(
                "MARKET",
                "LIMIT",
                "STOP",
                "STOP_LIMIT",
                "TRAILING_STOP",
                name="ordertype",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "order",
        sa.Column("alpaca_status", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "order",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_order_alpaca_order_id"), table_name="order")
    op.create_index(
        op.f("ix_order_alpaca_order_id"), "order", ["alpaca_order_id"], unique=False
    )
    op.create_index(op.f("ix_order_user_id"), "order", ["user_id"], unique=False)
    op.create_index(op.f("ix_order_symbol"), "order", ["symbol"], unique=False)
    op.create_index(
        op.f("ix_order_client_order_id"), "order", ["client_order_id"], unique=False
    )
    op.alter_column(
        "order", "alpaca_order_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "order",
        "side",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=postgresql.ENUM("BUY", "SELL", name="orderside"),
        existing_nullable=False,
        postgresql_using="side::orderside",
    )
    op.alter_column(
        "order",
        "qty",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
        postgresql_using="qty::double precision",
    )
    op.drop_column("order", "extended_hours")
    op.drop_column("order", "canceled_at")
    op.drop_column("order", "filled_at")
    op.drop_column("order", "submitted_at")
    op.drop_column("order", "filled_avg_price")
    op.drop_column("order", "filled_qty")
    op.drop_column("order", "time_in_force")
    op.drop_column("order", "type")
    # ### end Alembic commands ###
