"""Add RefreshToken table

Revision ID: 36bc8f2a74fc
Revises: 63d724bf8a98
Create Date: 2026-02-02 19:19:44.529218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "36bc8f2a74fc"
down_revision: Union[str, Sequence[str], None] = "63d724bf8a98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
